<a href="https://colab.research.google.com/github/VinayakDubey07/Deep-Learning-Concepts/blob/main/dl_lab2_mlp_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
# TensorFlow and tf.keras
import tensorflow as tf
from tensorflow import keras
housing = fetch_california_housing() # loading the California Housing dataset

housing

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n

In [2]:
X_train_full, X_test, y_train_full, y_test = train_test_split(housing.data, housing.target) # test and train
X_train, X_valid, y_train, y_valid = train_test_split(X_train_full, y_train_full) # training and validation

In [3]:
len(X_train_full)
len(X_test)
len(X_train)
len(X_valid)
y_test

array([2.26 , 0.69 , 2.104, ..., 2.157, 0.953, 4.85 ])

In [4]:
scaler = StandardScaler() # Using the StandardScaler to scale the dataset
X_train = scaler.fit_transform(X_train)
X_valid = scaler.transform(X_valid)
X_test = scaler.transform(X_test)

In [5]:
X_train.shape, X_valid.shape, X_test.shape #20640 instances

((11610, 8), (3870, 8), (5160, 8))

In [6]:
# Creating the model using the Sequential API
model = keras.models.Sequential([
keras.layers.Dense(30, activation="relu", input_shape=X_train.shape[1:]),
keras.layers.Dense(1)
])
model.compile(loss="mean_squared_error", optimizer="sgd") # compiling the model
history = model.fit(X_train, y_train, epochs=20, validation_data=(X_valid, y_valid)) # fit the model

Epoch 1/20
363/363 [==============================] - 6s 13ms/step - loss: 1.0030 - val_loss: 0.5579
Epoch 2/20
363/363 [==============================] - 3s 8ms/step - loss: 0.5017 - val_loss: 0.4851
Epoch 3/20
363/363 [==============================] - 3s 10ms/step - loss: 0.4541 - val_loss: 0.4585
Epoch 4/20
363/363 [==============================] - 2s 4ms/step - loss: 0.4305 - val_loss: 0.4409
Epoch 5/20
363/363 [==============================] - 3s 9ms/step - loss: 0.4148 - val_loss: 0.4268
Epoch 6/20
363/363 [==============================] - 1s 4ms/step - loss: 0.4069 - val_loss: 0.4267
Epoch 7/20
363/363 [==============================] - 1s 4ms/step - loss: 0.4036 - val_loss: 0.4144
Epoch 8/20
363/363 [==============================] - 1s 3ms/step - loss: 0.3908 - val_loss: 0.4087
Epoch 9/20
363/363 [==============================] - 1s 3ms/step - loss: 0.3819 - val_loss: 0.4050
Epoch 10/20
363/363 [==============================] - 1s 4ms/step - loss: 0.3843 - val_loss: 0.40

In [7]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 30)                270       
                                                                 
 dense_1 (Dense)             (None, 1)                 31        
                                                                 
Total params: 301
Trainable params: 301
Non-trainable params: 0
_________________________________________________________________


In [8]:
mse_test = model.evaluate(X_test, y_test) # evaluating

162/162 [==============================] - 0s 1ms/step - loss: 0.5043


In [9]:
X_new = X_test[:3] # pretend these are new instances
y_pred = model.predict(X_new)

1/1 [==============================] - 0s 88ms/step


In [10]:
y_pred

array([[2.7016037],
       [0.5100306],
       [1.78226  ]], dtype=float32)

In [11]:
model.save("my_keras_model.h5")

In [12]:
!strings my_keras_model.h5

TREE
HEAP
model_weights
optimizer_weights
keras_version
backend
model_config
training_config
TREE
HEAP
dense
dense_1
top_level_model_weights
layer_names
backend
GCOL
2.12.0
tensorflow
{"class_name": "Sequential", "config": {"name": "sequential", "layers": [{"class_name": "InputLayer", "config": {"batch_input_shape": [null, 8], "dtype": "float32", "sparse": false, "ragged": false, "name": "dense_input"}}, {"class_name": "Dense", "config": {"name": "dense", "trainable": true, "dtype": "float32", "batch_input_shape": [null, 8], "units": 30, "activation": "relu", "use_bias": true, "kernel_initializer": {"class_name": "GlorotUniform", "config": {"seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "kernel_regularizer": null, "bias_regularizer": null, "activity_regularizer": null, "kernel_constraint": null, "bias_constraint": null}}, {"class_name": "Dense", "config": {"name": "dense_1", "trainable": true, "dtype": "float32", "units": 1, "activation": "linear", "use_bias

In [13]:
model1 = keras.models.load_model("my_keras_model.h5") # Loading the model

In [14]:
model.predict(X_new) # predicting using the model

1/1 [==============================] - 0s 26ms/step


array([[2.7016037],
       [0.5100306],
       [1.78226  ]], dtype=float32)

In [15]:
model.save_weights("my_keras_weights.ckpt") # saving the weights
model.load_weights("my_keras_weights.ckpt") # loading the saved weights

**Complex MLP using functional API**

In [16]:
#defining layers

input_= keras.layers.Input(shape=X_train.shape[1:])
hidden1 = keras.layers.Dense(30, activation="relu")(input_) 
hidden2 = keras.layers.Dense(30, activation="relu")(hidden1)
concat = keras.layers.concatenate([input_, hidden2])
output = keras.layers.Dense(1)(concat)
model = keras.models.Model(inputs=[input_], outputs=[output])

In [17]:
model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_1 (InputLayer)           [(None, 8)]          0           []                               
                                                                                                  
 dense_2 (Dense)                (None, 30)           270         ['input_1[0][0]']                
                                                                                                  
 dense_3 (Dense)                (None, 30)           930         ['dense_2[0][0]']                
                                                                                                  
 concatenate (Concatenate)      (None, 38)           0           ['input_1[0][0]',                
                                                                  'dense_3[0][0]']            

In [18]:
model.compile(loss="mean_squared_error", optimizer=keras.optimizers.SGD(learning_rate=1e-3))
history = model.fit(X_train, y_train,epochs=20,validation_data=[X_valid,y_valid])
mse_test=model.evaluate(X_test,y_test) 

Epoch 1/20
363/363 [==============================] - 1s 2ms/step - loss: 1.4300 - val_loss: 0.8383
Epoch 2/20
363/363 [==============================] - 1s 2ms/step - loss: 0.6917 - val_loss: 0.7317
Epoch 3/20
363/363 [==============================] - 1s 2ms/step - loss: 0.6385 - val_loss: 0.6675
Epoch 4/20
363/363 [==============================] - 1s 2ms/step - loss: 0.6114 - val_loss: 0.6353
Epoch 5/20
363/363 [==============================] - 1s 2ms/step - loss: 0.5894 - val_loss: 0.6133
Epoch 6/20
363/363 [==============================] - 1s 2ms/step - loss: 0.5710 - val_loss: 0.5989
Epoch 7/20
363/363 [==============================] - 1s 2ms/step - loss: 0.5535 - val_loss: 0.5793
Epoch 8/20
363/363 [==============================] - 1s 2ms/step - loss: 0.5423 - val_loss: 0.5674
Epoch 9/20
363/363 [==============================] - 1s 2ms/step - loss: 0.5299 - val_loss: 0.5561
Epoch 10/20
363/363 [==============================] - 1s 2ms/step - loss: 0.5216 - val_loss: 0.5510

In [19]:
mse_test

0.4512759745121002

In [20]:
y_pred=model.predict(X_test)

162/162 [==============================] - 0s 2ms/step


In [21]:
y_pred

array([[2.5266006 ],
       [0.56109643],
       [1.9931233 ],
       ...,
       [2.5645053 ],
       [1.3564849 ],
       [3.3625429 ]], dtype=float32)

**Creating a model with different no of layers**

In [22]:
input_A = keras.layers.Input(shape=[5], name="wide_input")
input_B = keras.layers.Input(shape=[6], name="deep_input")
hidden1 = keras.layers.Dense(30, activation="relu")(input_B)
hidden2 = keras.layers.Dense(30, activation="relu")(hidden1)
concat = keras.layers.concatenate([input_A, hidden2])
output = keras.layers.Dense(1, name="output")(concat)
model = keras.models.Model(inputs=[input_A, input_B], outputs=[output])

In [23]:
input_A

<KerasTensor: shape=(None, 5) dtype=float32 (created by layer 'wide_input')>

In [24]:
model.summary()

Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 deep_input (InputLayer)        [(None, 6)]          0           []                               
                                                                                                  
 dense_5 (Dense)                (None, 30)           210         ['deep_input[0][0]']             
                                                                                                  
 wide_input (InputLayer)        [(None, 5)]          0           []                               
                                                                                                  
 dense_6 (Dense)                (None, 30)           930         ['dense_5[0][0]']                
                                                                                            

In [25]:
model.compile(loss="mae", optimizer=keras.optimizers.SGD(learning_rate=1e-3))

In [26]:
X_train_A, X_train_B = X_train[:, :5] , X_train[:, 2:]
X_valid_A, X_valid_B = X_valid[:, :5] , X_valid[:, 2:]
X_test_A , X_test_B = X_test[:, :5] , X_test[:, 2:]
X_new_A, X_new_B = X_test_A[:3] , X_test_B[:3]

In [27]:
history = model.fit((X_train_A, X_train_B), y_train,epochs=20,validation_data=((X_valid_A, X_valid_B), y_valid))
mse_test = model.evaluate((X_test_A, X_test_B), y_test)
y_pred = model.predict((X_new_A, X_new_B))

Epoch 1/20
363/363 [==============================] - 2s 3ms/step - loss: 1.5430 - val_loss: 1.1902
Epoch 2/20
363/363 [==============================] - 1s 2ms/step - loss: 0.9736 - val_loss: 0.8656
Epoch 3/20
363/363 [==============================] - 1s 2ms/step - loss: 0.8034 - val_loss: 0.7715
Epoch 4/20
363/363 [==============================] - 1s 2ms/step - loss: 0.7384 - val_loss: 0.7202
Epoch 5/20
363/363 [==============================] - 1s 2ms/step - loss: 0.6992 - val_loss: 0.6876
Epoch 6/20
363/363 [==============================] - 1s 2ms/step - loss: 0.6713 - val_loss: 0.6639
Epoch 7/20
363/363 [==============================] - 1s 2ms/step - loss: 0.6503 - val_loss: 0.6456
Epoch 8/20
363/363 [==============================] - 1s 2ms/step - loss: 0.6332 - val_loss: 0.6308
Epoch 9/20
363/363 [==============================] - 1s 2ms/step - loss: 0.6188 - val_loss: 0.6173
Epoch 10/20
363/363 [==============================] - 1s 2ms/step - loss: 0.6057 - val_loss: 0.6050

In [28]:
y_pred

array([[2.364515 ],
       [0.6209118],
       [1.808229 ]], dtype=float32)

In [29]:
output = keras.layers.Dense(1, name="main_output")(concat)
aux_output = keras.layers.Dense(1, name="aux_output")(hidden2)
model = keras.Model(inputs=[input_A, input_B], outputs=[output, aux_output])

In [30]:
model.compile(loss=["mae","mse"], loss_weights=[], optimizer=keras.optimizers.SGD(learning_rate=1e-3))

**Using Callbacks during Training**

In [31]:
import numpy as np

keras.backend.clear_session()
np.random.seed(42)
tf.random.set_seed(42)

In [32]:
# Defining the model to demostrate callbacks
model = keras.models.Sequential([
keras.layers.Dense(30, activation="relu", input_shape=[8]),
keras.layers.Dense(30, activation="relu"),
keras.layers.Dense(1)
])

model.compile(loss="mse", optimizer=keras.optimizers.SGD(lr=1e-3))
checkpoint_cb = keras.callbacks.ModelCheckpoint("my_keras_model.h5", save_best_only=True) # saving the best model checkpoint
history = model.fit(X_train, y_train, epochs=10,
validation_data=(X_valid, y_valid),
callbacks=[checkpoint_cb]) # using the callback
model = keras.models.load_model("my_keras_model.h5") # rollback to best model
mse_test = model.evaluate(X_test, y_test)

Epoch 1/10
363/363 [==============================] - 1s 2ms/step - loss: 0.7189 - val_loss: 0.4994
Epoch 2/10
363/363 [==============================] - 1s 2ms/step - loss: 0.4607 - val_loss: 0.4356
Epoch 3/10
363/363 [==============================] - 1s 3ms/step - loss: 0.4035 - val_loss: 0.4095
Epoch 4/10
363/363 [==============================] - 1s 3ms/step - loss: 0.3783 - val_loss: 0.3984
Epoch 5/10
363/363 [==============================] - 1s 2ms/step - loss: 0.3959 - val_loss: 0.4529
Epoch 6/10
363/363 [==============================] - 1s 2ms/step - loss: 0.3714 - val_loss: 0.3932
Epoch 7/10
363/363 [==============================] - 1s 2ms/step - loss: 0.3716 - val_loss: 0.3803
Epoch 8/10
363/363 [==============================] - 1s 2ms/step - loss: 0.3606 - val_loss: 0.3794
Epoch 9/10
363/363 [==============================] - 1s 2ms/step - loss: 0.3462 - val_loss: 0.3699
Epoch 10/10
162/162 [==============================] - 0s 1ms/step - loss: 0.3452


In [33]:
model.compile(loss="mse", optimizer=keras.optimizers.SGD(lr=1e-3))
early_stopping_cb = keras.callbacks.EarlyStopping(patience=5,

restore_best_weights=True) # saving early stopping

history = model.fit(X_train, y_train, epochs=100,
validation_data=(X_valid, y_valid),
callbacks=[checkpoint_cb, early_stopping_cb]) # using the callback for checkpoint, and early stopping

mse_test = model.evaluate(X_test, y_test)

Epoch 1/100
363/363 [==============================] - 1s 2ms/step - loss: 0.3418 - val_loss: 0.3634
Epoch 2/100
363/363 [==============================] - 1s 2ms/step - loss: 0.3361 - val_loss: 0.3648
Epoch 3/100
363/363 [==============================] - 1s 2ms/step - loss: 0.3325 - val_loss: 0.3560
Epoch 4/100
363/363 [==============================] - 1s 2ms/step - loss: 0.3284 - val_loss: 0.3551
Epoch 5/100
363/363 [==============================] - 1s 3ms/step - loss: 0.3258 - val_loss: 0.3593
Epoch 6/100
363/363 [==============================] - 1s 3ms/step - loss: 0.3275 - val_loss: 0.3534
Epoch 7/100
363/363 [==============================] - 1s 3ms/step - loss: 0.3230 - val_loss: 0.3504
Epoch 8/100
363/363 [==============================] - 1s 2ms/step - loss: 0.3198 - val_loss: 0.3512
Epoch 9/100
363/363 [==============================] - 1s 2ms/step - loss: 0.3175 - val_loss: 0.3459
Epoch 10/100
363/363 [==============================] - 1s 2ms/step - loss: 0.3147 - val_lo

**Trying Hyper-parameter Tuning**

In [34]:
def build_model(n_hidden=1, n_neurons=30, learning_rate=3e-3, input_shape=[8]):
  model = keras.models.Sequential()
  model.add(keras.layers.InputLayer(input_shape=input_shape))
  for layer in range(n_hidden):
    model.add(keras.layers.Dense(n_neurons, activation="relu"))
  model.add(keras.layers.Dense(1))
  optimizer = keras.optimizers.SGD(learning_rate=learning_rate)
  model.compile(loss="mse", optimizer=optimizer)
  return model

keras_reg = keras.wrappers.scikit_learn.KerasRegressor(build_model)

<ipython-input-34-ddb07a810127>:11: DeprecationWarning: KerasRegressor is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.
  keras_reg = keras.wrappers.scikit_learn.KerasRegressor(build_model)


In [ ]:
keras_reg.fit(X_train, y_train, epochs=100,
validation_data=(X_valid, y_valid),
callbacks=[keras.callbacks.EarlyStopping(patience=10)])

In [36]:
mse_test = keras_reg.score(X_test, y_test)

162/162 [==============================] - 0s 1ms/step - loss: 0.3498


In [37]:
y_pred = keras_reg.predict(X_new)

1/1 [==============================] - 0s 61ms/step


In [38]:
from scipy.stats import reciprocal
from sklearn.model_selection import RandomizedSearchCV
param_distribs = {
"n_hidden": [0, 1, 2, 3],
"n_neurons": np.arange(1, 100),
"learning_rate": reciprocal(3e-4, 3e-2),
}
rnd_search_cv = RandomizedSearchCV(keras_reg, param_distribs, n_iter=3, cv=2, verbose=2)

rnd_search_cv.fit(X_train, y_train, epochs=10,
validation_data=(X_valid, y_valid),
callbacks=[keras.callbacks.EarlyStopping(patience=3)])

Fitting 2 folds for each of 3 candidates, totalling 6 fits
Epoch 1/10
182/182 [==============================] - 1s 3ms/step - loss: 5.6397 - val_loss: 3.3362
Epoch 2/10
182/182 [==============================] - 0s 2ms/step - loss: 1.9844 - val_loss: 1.5092
Epoch 3/10
182/182 [==============================] - 1s 3ms/step - loss: 1.0559 - val_loss: 0.9201
Epoch 4/10
182/182 [==============================] - 0s 2ms/step - loss: 0.7627 - val_loss: 0.7168
Epoch 5/10
182/182 [==============================] - 0s 2ms/step - loss: 0.6648 - val_loss: 0.6470
Epoch 6/10
182/182 [==============================] - 0s 2ms/step - loss: 0.6262 - val_loss: 0.6170
Epoch 7/10
182/182 [==============================] - 0s 2ms/step - loss: 0.6085 - val_loss: 0.6033
Epoch 8/10
182/182 [==============================] - 0s 2ms/step - loss: 0.5975 - val_loss: 0.5942
Epoch 9/10
182/182 [==============================] - 0s 2ms/step - loss: 0.5898 - val_loss: 0.5876
Epoch 10/10
182/182 [====================

RandomizedSearchCV(cv=2,
                   estimator=<keras.wrappers.scikit_learn.KerasRegressor object at 0x7fc089e263e0>,
                   n_iter=3,
                   param_distributions={'learning_rate': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x7fc089d20d60>,
                                        'n_hidden': [0, 1, 2, 3],
                                        'n_neurons': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])},
                   verbose=2)

In [39]:
rnd_search_cv.best_params_

{'learning_rate': 0.001683454924600351, 'n_hidden': 0, 'n_neurons': 15}

In [40]:
rnd_search_cv.best_score_

-0.5774253010749817

In [41]:
model = rnd_search_cv.best_estimator_.model
model